### ISSUE TITLE
libmagic dependency on OS X

### ISSUE THREAD

**Issue by Fil** [paulfitz/catsql#2]
after installing on OS X with `pip install catsql` I got this error:
```
Traceback (most recent call last):
  File "/usr/local/bin/catsql", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/catsql/main.py", line 312, in main
    catsql()
  File "/usr/local/lib/python2.7/site-packages/catsql/main.py", line 122, in catsql
    import magic
  File "/usr/local/lib/python2.7/site-packages/magic.py", line 169, in <module>
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation
```

I then followed
http://www.brambraakman.com/blog/comments/installing_libmagic_in_mac_os_x_for_python-magic/
and did `brew install libmagic` and it worked.

**Comment by paulfitz** [comment]
Thanks for testing @Fil!

**Comment by paulfitz** [comment]
`pip install catsql --upgrade` should know give a version without libmagic. I realize that I omitted to say that if you don't already have drivers for the database you care about, you can do something like `pip install catsql[postgres]` or `catsql[mysql]`.

**Comment by paulfitz** [comment]
Tested latest version of `catsql` on OSX. Install goes fine, and sqlite works fine. Installing postgres driver was less than trivial, easiest (but not necessarily fastest) was to `pip install pg8000` and then use `postgresql+pg8000://...` urls.
